# Generated by Django 3.2.5 on 2021-11-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteAIModel',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('dataset_name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'model',
                'verbose_name_plural': 'models',
                'db_table': 'remote_ai_remote_ai_model',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
