# Generated by Django 4.0.7 on 2022-10-11 07:31

from django.db import migrations, models
import django.db.models.deletion
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_alter_group_config_alter_group_name_and_more'),
        ('dataset', '0005_alter_dataset_config_alter_dataset_groups_and_more'),
        ('remote_ai_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteaimodel',
            name='config',
            field=systems.models.fields.DictionaryField(default=dict),
        ),
        migrations.AlterField(
            model_name='remoteaimodel',
            name='dataset',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(data_name)s', to='dataset.dataset'),
        ),
        migrations.AlterField(
            model_name='remoteaimodel',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='%(data_name)s', to='group.group'),
        ),
        migrations.AlterField(
            model_name='remoteaimodel',
            name='provider_type',
            field=models.CharField(default='base', max_length=128),
        ),
        migrations.AlterField(
            model_name='remoteaimodel',
            name='variables',
            field=systems.models.fields.DictionaryField(default=dict, editable=False),
        ),
    ]
