# Generated by Django 3.2.5 on 2021-12-02 10:32

from django.db import migrations, models
import django.db.models.deletion
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0001_initial'),
        ('group', '0001_initial'),
        ('remote_ai_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remoteaimodel',
            options={'ordering': ['name', '-created'], 'verbose_name': 'remote ai model', 'verbose_name_plural': 'remote ai models'},
        ),
        migrations.RemoveField(
            model_name='remoteaimodel',
            name='dataset_name',
        ),
        migrations.AddField(
            model_name='remoteaimodel',
            name='config',
            field=systems.models.fields.EncryptedDataField(default={}, editable=False),
        ),
        migrations.AddField(
            model_name='remoteaimodel',
            name='dataset',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remoteaimodel_relation', to='dataset.dataset'),
        ),
        migrations.AddField(
            model_name='remoteaimodel',
            name='groups',
            field=models.ManyToManyField(related_name='remoteaimodel_relations', to='group.Group'),
        ),
        migrations.AddField(
            model_name='remoteaimodel',
            name='provider_type',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='remoteaimodel',
            name='state_config',
            field=systems.models.fields.EncryptedDataField(default={}, editable=False),
        ),
        migrations.AddField(
            model_name='remoteaimodel',
            name='training_percentage',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='remoteaimodel',
            name='variables',
            field=systems.models.fields.EncryptedDataField(default={}, editable=False),
        ),
    ]
