# Generated by Django 3.2.5 on 2021-12-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_ai_model', '0002_auto_20211202_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteaimodel',
            name='f1_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remoteaimodel',
            name='precision',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remoteaimodel',
            name='recall',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='remoteaimodel',
            name='training_percentage',
            field=models.FloatField(default=0.7),
        ),
    ]
