config:
    data: [usa_jobs_search]

    features:
        text_remote_data:
            module: remote_ai
            profile: features/text_remote

    models:
        tfidf_svc:
            feature_set: text_remote_data
            provider: tfidf_svc
            groups: [svc, tfidf]

    import_data: true
    generate_features: true
    save_models: true
    training_percentage: 0.75

    remove_features: true
    remove_models: true
